function urlArgs(){
    return function (name, path) {
        if (this.paths[name] && this.paths[name].indexOf("?v=") > -1) {
            return '';
        }
        return "?v=1737627122501";
    }
}

var require = {
	baseUrl : "../../",
    map: {
      	'*': { 'style': 'assets/lib/requirejs/css.min' }
    },
	paths: {
		 'crossAPI':'assets/common/crossAPI.js?v=d727bab',
		'jquery':'assets/lib/jqr/jqr.js?v=4f25252',
		'backbone':'assets/lib/backbone/a.js?v=95a66c2',
		'laydate':'assets/lib/laydate/laydate.js?v=c2216b1',
		'niceScroll':'assets/lib/niceScroll/jquery.nicescroll.js?v=d5c3139',
		'text':'assets/lib/requirejs/text.js?v=3aa213f',
		'artDialog':'assets/lib/dialog/dialog-plus.js?v=1f5aabf',
		'zTree':'assets/lib/zTree_v3/js/jquery.ztree.all.js?v=0914e93',
		'simpleTree':'assets/components/simpleTree/simpleTree.js?v=277623b',
		'ueditorConfig':'assets/lib/ueditor/ueditor.config?v=1737627122501',
		'ueditor':'assets/lib/ueditor/ueditor.all?v=1737627122501',
		'echarts':'assets/lib/echarts/echarts.js?v=2ee8dce',
		'echarts_5.0.1':'assets/lib/echarts/echarts_4.9.0.js?v=b5b3475',
		'jquery.jplayer':'assets/lib/jqueryPlugin/jPlayer/dist/jplayer/jquery.jplayer.js?v=f39a347',
		"jquery.placeholder":"assets/lib/jqueryPlugin/placeholder/jquery.placeholder.min.js?v=f9e2f79",
		"jquery.fileuploader":"assets/lib/jqueryPlugin/jQuery-File-Upload/js/jquery.fileupload.js?v=99c7410",
		"jquery.ui.widget":"assets/lib/jqueryPlugin/jQuery-File-Upload/js/vendor/jquery.ui.widget.js?v=90739a5",
		"jquery.pagination":"assets/lib/jqueryPlugin/pagination/jquery.pagination.js?v=40b8efd",
		'jqueryUI':'assets/lib/jqueryui/jquery-ui.min.js?v=796b299',
		'jquery.dragsort':'assets/lib/dragsort/jquery.dragsort-0.5.2.min.js?v=9ac10dd',
		'jquery.dragsortDialogyk':'assets/lib/dragsortDialog/jquery.dragsort.js?v=0737bc3',
		'bootstrap':'assets/lib/bootstrap/bootstrap.min.js?v=5869c96',
		'bootstrap-table':'assets/lib/bootstrap/plugin/bootstrap-table/bootstrap-table.js?v=35440fb',
		'page-jumpto':'assets/lib/bootstrap/plugin/bootstrap-table/extensions/page-jumpto/bootstrap-table-jumpto.js?v=cf164bd',
		'table':'assets/lib/bootstrap/plugin/bootstrap-table/locale/bootstrap-table-zh-CN.js?v=70d1db3',
		'bootstrap-table-export':'assets/lib/bootstrap/plugin/bootstrap-table/extensions/export/bootstrap-table-export?v=1737627122501',
		'fileinput':'assets/lib/bootstrap/plugin/fileinput/fileinput.js?v=e692b72',
		'fileinput_local':'assets/common/fileinput_local_zh.js?v=39ed957',
		'bootstrap-paginator':'assets/common/bootstrap-paginator.js?v=bbc0f95',
		'cookie':'assets/common/cookie.js?v=375885c',
		'ajax':'assets/common/ajax_amd.js?v=301e0fa',
		'ajax_config':'assets/common/ajax_config.js?v=8703ae7',
		'base64':'assets/common/base64.js?v=e131e62',
		'hdb':'assets/lib/handlebars/handlebars.js?v=0a63d1c',
		'hdbr':'assets/lib/handlebars/handlebars.runtime.js?v=63bfd5e',
		'eventTarget':'assets/common/eventTarget.js?v=a685f11',
		'form':'assets/common/form_amd.js?v=5ca559b',
		'keyboardEvent':'assets/common/keyBoardEvent_amd.js?v=b4bff33',
		'hdbHelper':'assets/lib/handlebars/helpers.js?v=19d0c99',
		'underscore':'assets/lib/underscore/underscore.js?v=62e1072',
		'json2':'assets/lib/json2/json2.js?v=74305c9',
		'type':'assets/common/type.js?v=4f04e97',
		'event':'assets/common/event.js?v=efcbb7a',
		'extend':'assets/common/extend.js?v=4c6c895',
		'routes':'assets/common/routes.js?v=2332b46',
		'tab':'assets/components/tab/tab.js?v=1b06e02',
		'encrypt':'assets/common/encrypt.js?v=60ab5db',
		'radios':'assets/components/radios/radios.js?v=c3d21a1',
		'list':'assets/components/list/list.js?v=1ae233e',
		'select':'assets/components/select/select.js?v=6adc589',
		'date':'assets/components/date/date.js?v=a47f192',
		'dialog':'assets/components/dialog/dialog.js?v=711db3a',
		'editor':'assets/components/editor/editor.js?v=e83ab21',
		'kindEditor':'assets/lib/kindeditor/kindeditor-all.js?v=689d643',
		'kindEditorLang':'assets/lib/kindeditor/lang/zh-CN.js?v=1dd425c',
		'validator':'assets/components/validator/validator.js?v=6c0de4a',
		'comSelectTree':'assets/components/selectTree/selectTree.js?v=ecfa6b4',
		'selectTree':'assets/components/customSelectTree/customSelectTree.js?v=e59196b',
		'voice':'assets/components/voice/voice.js?v=2cc451b',
		'video':'assets/components/video/video.js?v=3f58454',
		'image':'assets/components/image/image.js?v=43fc4f5',
		'viewer':'assets/lib/viewer/viewer.js?v=cf30a68',
		'volumeSlot':'assets/components/volumeSlot/volumeSlot.js?v=128fcf5',
		'gwm':'assets/components/waterMark/gwm.js?v=b7a6abc',
		'waterMarksNew':'assets/components/waterMark/waterMarksNew.js?v=712c618',
		'counter':'assets/components/counter/counter.js?v=284f4dd',
		'comboSelect':'assets/components/comboSelect/comboSelect.js?v=265c9ee',
		'jqComboSelect':'assets/lib/comboSelect/jquery.combo.select.js?v=1b1c256',
		'selectMultiple':'assets/components/selectMultiple/selectMultiple.js?v=cce4705',
		'timer':'assets/components/timer/timer.js?v=ad9f345',
		'loading':'assets/components/loading/loading.js?v=1554e9f',
		'satisfyStar':'assets/components/satisfyStar/satisfyStar.js?v=a5a2ea8',
		'upload':'assets/components/upload/upload.js?v=32c280e',
		'buttonGroup':'assets/components/buttonGroup/buttonGroup.js?v=366bbed',
		'checkboxes':'assets/components/checkboxes/checkboxes.js?v=4a70648',
		'groupSearchForm':'assets/components/groupSearchForm/groupSearchForm.js?v=bf42787',
		'process':'assets/components/process/process.js?v=4bd1866',
		'detailPanel':'assets/components/detailPanel/detailPanel.js?v=12ecea5',
		'Util':'assets/common/util.js?v=0f4a409',
		'jquery.iframe-transport':'assets/lib/jqueryPlugin/jQuery-File-Upload/js/jquery.iframe-transport.js?v=2e0baf0',
		'lazyLoad':'assets/components/lazyLoad/lazyLoad.js?v=157ecaa',
		'waterMarks':'assets/components/waterMarks/waterMarks.js?v=2b382f2',
		'tip':'assets/components/tip/tip.js?v=8a44a2e',
		'switch':'assets/components/switch/switch.js?v=962200e',
		'businessSelectTree':'js/components/selectTree.js?v=9e4e7b9',
		'businessSelect':'js/components/select.js?v=f98258a',
		'pagination':'js/components/page/page.js?v=51fe4cb',
		'knowledgeTree':'js/components/knowledgeTree/js/knowledgeTree.js?v=9ba6133',
		'solid':"js/components/solid/solid.js?v=275bbf4",
		'region':'assets/components/region/region.js?v=2cf04f9',
		'colResizable':"js/components/colResizable/colResizable-1.6.js?v=400597e",
		'btnAuth':'js/btnAuthority.js?v=91ae89f',
		'Log':'assets/common/log.js?v=8e89f8d',
		'transfer':'assets/components/transfer/transfer.js?v=c63e74a',
		'zTree-hide':'assets/lib/zTree_v3/js/jquery.ztree.exhide-3.5.js?v=f5f38b2',
		'protocolcheck':'js/protocolcheck/protocolcheck.js?v=920fd22',
		'znydDialog':'assets/common/znyd_dialog.js?v=50853eb',
		'colorPick':'assets/common/colorPicker?v=1737627122501' 
},
	waitSeconds:0,
	shim:{
        //'jquery.fileuploader': { deps: ['jquery.ui.widget'] },
        'jquery.fileuploader': { deps: ['jquery'] },
        'jquery.ui.widget': { deps: ['jquery'] },
        'jquery.placeholder': { deps: ['jquery'] },
        'jquery.jplayer': { deps: ['jquery'] },
        'jquery.pagination': { deps: ['jquery'] },
        'pagination': { deps: ['jquery'] },
        'jquery.iframe-transport': { deps: ['jquery'] },
        'validator': { deps: ['jquery'] },
        'kindEditorLang': { deps: ['kindEditor'] },
        'bootstrap': { deps: ['jquery'] },
        'bootstrap-table': { deps: ['jquery','bootstrap','style!assets/lib/bootstrap/plugin/bootstrap-table/bootstrap-table.min.css'] },
        'ueditor': { deps: ['ueditorConfig'] },
        'hdb':{ exports: ['Handlebars'] },
        'hdbHelper': { deps: ['hdb'] },
        //'ajax': { deps: ['jquery'] },
        'ajax': { deps: ['jquery','event'] },
        'artDialog': { deps: ['jquery'] },
        'zTree' : { deps:['jquery'], exports:'$.fn.zTree' },
        'zTree-hide': {deps: ['zTree']},
        'jqueryUI': { deps: ['jquery'] },
        'jqLazyLoad':{deps: ['jquery']},
        'lazyLoad':{deps: ['jquery']},
        'page-jumpto':{ deps: ['jquery','bootstrap-table','style!assets/lib/bootstrap/plugin/bootstrap-table/extensions/page-jumpto/bootstrap-table-jumpto.css'] },
        'table': { deps: ['page-jumpto'] },
        'bootstrap-table-export': { deps: ['jquery','table'] },
        'tableExport':{deps: ['xlsx_core','Blob','FileSaver','bootstrap-table-export','style!assets/lib/tableexport/tableexport.css'] },
        'fileinput':{deps: ['xlsx_full','style!assets/lib/bootstrap/plugin/fileinput/fileinput.css','jquery','bootstrap']},
        'fileinput_local':{deps: ['fileinput']},
        //'layer' : { deps: ['jquery','style!assets/lib/layer/theme/default/layer.css'] },
        'colResizable': { deps: ['jquery'] },
        //colResizable-znyd': { deps: ['jquery'] },
        //'resizable':{deps:['colResizable-znyd']}
        },
    urlArgs: urlArgs()

};
var requireConfig = require;
